dataset:
  target: dataset.licdataset.LICDataset
  params:
    # Path to the file list.
    file_list: ./datalists/img_set3_train_split.list
    out_size: 512
    crop_type: center
    use_hflip: True
    use_rot: False

data_loader:
  batch_size: 1
  shuffle: true
  num_workers: 8
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform

