dataset:
  target: dataset.licdataset.LICDataset
  params:
    # Path to the OOD satellite training file list
    file_list: ./datalists/ood_satellite_train.list
    out_size: 512
    crop_type: random
    use_hflip: True
    use_rot: False

data_loader:
  batch_size: 1
  shuffle: true
  num_workers: 4
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform


